---
- name: Add bricks to a volume
  gluster_volume:
        state: present
        volume: "{{ gluster_cluster_volume }}"
        bricks: "{{ gluster_cluster_new_bricks }}"
        remove_bricks: "{{ gluster_cluster_remove_bricks | default('no') }}"
        cluster: "{{ gluster_cluster_hosts }}"
        force: "{{ gluster_cluster_force | default('no') }}"
